runtime: python39
service: inventarisasi-fe
instance_class: F1

handlers:
  - url: /
    static_files: pages/login.html
    upload: pages/login.html
  - url: /(.*)
    static_files: \1
    upload: (.*)
    
default_expiration: "1h"