runtime: python39
service: inventarisasi-fe
instance_class: F1

handlers:
  # Serve the main page
  - url: /
    static_files: login.html
    upload: login\.html

  # Serve all static files
  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"