runtime: python39
service: inventarisasi-fe
instance_class: F1

handlers:
  # Serve CSS files
  - url: /css
    static_dir: css
    
  # Serve JS files  
  - url: /js
    static_dir: js
    
  # Serve pages directory
  - url: /pages
    static_dir: pages
    
  # Root URL mengarah ke login.html di folder pages
  - url: /
    static_files: pages/login.html
    upload: pages/login\.html
    
  # Route untuk halaman-halaman lain
  - url: /login
    static_files: pages/login.html
    upload: pages/login\.html
    
  - url: /register  
    static_files: pages/register.html
    upload: pages/register\.html
    
  - url: /barang
    static_files: pages/barang.html
    upload: pages/barang\.html
    
  - url: /edit-barang
    static_files: pages/edit-barang.html
    upload: pages/edit-barang\.html
    
  - url: /tambah-barang
    static_files: pages/tambah-barang.html
    upload: pages/tambah-barang\.html
    
  # Serve semua file statis lainnya
  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"